### PR TITLE
feat(library): improve first-run and power-user workflows

### PR DESCRIPTION
**Pull request by rmusser01**
## Summary

- add lifecycle-aware first-run Library disclosure with a compact Get started rail, truthful six-owner content evidence, and persistent recovery/status feedback
- distill paged empty and recovery states, then simplify Prompt and Skill editing with Basic/Advanced disclosure while preserving expert workflows
- preserve wide Notes browse continuity across editor and Files tasks, including exact filter, sort, identity, scroll, rail, and semantic-focus restoration
- retain hidden-route/deep-link authority, mutation and dirty-state guards, keyboard focus vetoes, and compact-terminal behavior
- align the rebased test harness authority and make the generated widget CSS reproducible without trailing whitespace

## Backlog tasks

- TASK-19022 — Library starter rail and lifecycle-aware landing
- TASK-19023 — Distilled paged Library empty states
- TASK-19024 — Simplified Library Prompt editing
- TASK-19025 — Simplified Library Skill editing
- TASK-19026 — Wide Library Notes browse continuity

## Verification

- 447 changed non-UI/direct-owner tests passed
- 159 Prompt editor/canvas tests passed
- 87 Skill editor/canvas tests passed
- 155 paged-empty/recovery tests passed
- 131 lifecycle/Starter Library shell tests and 37 rail/entry/palette tests passed
- 43 Notes continuity tests passed
- 14 Conversations direct-owner, 8 Persona visual-pack, and 10 CSS integrity tests passed
- final post-rebase smoke: 19 passed
- Ruff passed every Python file changed from `origin/dev`
- generated app/widget/screen CSS parity passed
- `git diff origin/dev...HEAD --check` passed

Per user direction, the repository-wide pytest suite was not run; verification is limited to modified/touched Library components and direct owners.

---
## Summary by cubic
Lifecycle-aware Library UX for first‑run and power users, plus simpler Prompt/Skill editors without sacrificing power tools. Old: new profiles saw the full Library and zero‑result paging with false “empty” claims; Notes editing hid navigation. New: a compact Get started rail/landing driven by tri‑state evidence, distilled empty states with one recovery, and wide Notes browse that keeps the rail and restores exact context.

- Starter lifecycle: persist `LibraryLifecycle` (`unknown|starter|expanded|graduated`); admission via `first_profile_created_this_session`; any usable content permanently graduates; deletion never demotes. Compact rail (Import, New note, Explore) and landing show live source checks with Retry; deep links and palette commands can open hidden routes under Starter. (TASK‑19022)
- Evidence contracts: `LibraryContentEvidence`/`LibraryEvidenceStatus` across Notes/Media/Conversations/Prompts/Skills/Collections drive lifecycle and empty states. Media counts active, non‑Trash with completed chunking; Skills count available, non‑blocked managed skills; Collections only active; Conversations require exact saved totals; server Notes return `count_exact`. (TASK‑19022)
- Paged empty states: Media, Conversations, Prompts show a single source‑specific action on fresh unfiltered zero; filtered‑zero preserves the filter with a clear reset; loading/error keep Retry; retained stale keeps rows/pager. (TASK‑19023)
- Editors: Prompt/Skill Basic/Advanced share one mounted draft (`coerce_*_editor_mode`); no text editor remounts. Forced Advanced for recipes/incompatibility/conflict/safety with an explicit reason; embedded Prompt editor supports host‑owned lifecycle; Advanced Skills tool picker uses native `SelectionList`; invocation copy clarifies user vs agent; allowlist reconciliation preserves ordering and unknowns. (TASK‑19024, TASK‑19025)
- Notes continuity: wide browse keeps the rail; editor and Files use a focused canvas with a persistent Library/Notes return cue; Back restores source, filter, sort, identity, scroll, rail position, and semantic focus; guards unchanged. (TASK‑19026)
- Guardrails and docs/tests: command palette destinations, hidden‑route authority, compact‑terminal behavior, and dirty/sync/conflict/mutation guards are preserved; specs/plans and extensive UI/service tests were added.

- Rollout
  - No DB migrations. Config adds `library.rail_state.lifecycle`; missing/corrupt coerces to `expanded`. Session‑scoped admission via `first_profile_created_this_session`. No action required for existing profiles. Generated CSS updated and remains reproducible.

<sup>Written for commit 2af56fbfb437b755b2c2a6befcb78165b100e958. Summary will update on new commits.</sup>

<a href="https://cubic.dev/pr/rmusser01/tldw_chatbook/pull/1893?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

File: tldw_chatbook/Notes/notes_scope_service.py [hunk 1]
```diff
@@ -1268,6 +1274,59 @@ async def count_notes(
...
         )
 
+    async def get_library_user_content_evidence(
+        self,
+        *,
+        scope: ScopeType | str,
+        user_id: Optional[str] = None,
+    ) -> LibraryContentEvidence:
+        """Return tri-state evidence for accessible active user notes."""
+        normalized_scope = self._normalize_scope(scope)
```
[the remark this answers is not in the document]
Comment (rmusser01) [reply tldw_chatbook/Notes/notes_scope_service.py:1293]: Fixed in ddfc5043e. Added Google-style / documentation to the Notes evidence seam and  sections to the Collections protocol/implementation and the session-profile accessor. I also documented Prompt evidence's server-provenance constraint while touching that reviewed public API. Affected owner tests and Ruff are green.

File: tldw_chatbook/UI/Screens/library_screen.py [hunk 2]
```diff
@@ -15003,68 +15394,448 @@ def handle_library_note_use_in_console(self, event: Button.Pressed) -> None:
...
+                        result = task.result()
+                    except Exception:
+                        result = LibraryContentEvidence.UNKNOWN
+                    evidence.append(result)
+                    if result is LibraryContentEvidence.HAS_USER_CONTENT:
+                        self._apply_library_onboarding_evidence(
+                            generation,
+                            admission_key,
+                            [result],
+                        )
```
[the remark this answers is not in the document]
Comment (rmusser01) [reply tldw_chatbook/UI/Screens/library_screen.py:15641]: Addressed the representation concern in ddfc5043e without changing the intended bounded positive short-circuit. ADR-076 explicitly states that one authoritative positive may graduate immediately, so waiting for a hanging owner would regress the approved behavior. The gatherer now passes an exact six-slot vector ( plus  for unfinished owners) before cancelling/draining the remaining tasks. The focused test first failed on the prior one-item vector, then passed; adjacent positive/timeout/partial-failure cases are green.

File: tldw_chatbook/Prompt_Management/prompt_scope_service.py [hunk 3]
```diff
@@ -1450,7 +1452,56 @@ async def count_prompts(self, *, mode: PromptBackend | str = "local") -> int:
...
+            or len(items) > 1
+        ):
+            return LibraryContentEvidence.UNKNOWN
+        if total == 0:
+            return (
+                LibraryContentEvidence.EMPTY
+                if not items
+                else LibraryContentEvidence.UNKNOWN
+            )
+        return LibraryContentEvidence.UNKNOWN
```
[the remark this answers is not in the document]
Comment (rmusser01) [reply tldw_chatbook/Prompt_Management/prompt_scope_service.py:1516]: Not changing this to : the deployed /server summary exposes prompt records and totals but no ownership/provenance marker. ADR-076 requires sources that cannot distinguish bundled/system/sample from eligible user content to return , and  pins both mapping and real Pydantic server summaries as ambiguous. Treating every non-empty server page as user-owned would create a false graduation. I added this rationale to the public method docstring in ddfc5043e; the focused production-model regression remains green.

File: tldw_chatbook/Notes/notes_scope_service.py (hunk 1 above)
[the remark this answers is not in the document]
Comment (rmusser01) [reply tldw_chatbook/Notes/notes_scope_service.py:1293]: Clarification: ddfc5043e adds Google-style Args and Returns sections to the Notes evidence seam, Returns sections to both Collections declarations, and Returns documentation to first_profile_created_this_session. The affected owner tests and Ruff checks pass.

File: tldw_chatbook/UI/Screens/library_screen.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (rmusser01) [reply tldw_chatbook/UI/Screens/library_screen.py:15641]: Clarification: the exact six-slot vector is one HAS_USER_CONTENT value plus five UNKNOWN values for unfinished owners. This preserves ADR-076 immediate positive graduation while satisfying the six-source representation contract.

File: tldw_chatbook/Prompt_Management/prompt_scope_service.py (hunk 3 above)
[the remark this answers is not in the document]
Comment (rmusser01) [reply tldw_chatbook/Prompt_Management/prompt_scope_service.py:1516]: Clarification: the deployed PromptBriefResponse has no ownership field. ADR-076 therefore requires UNKNOWN for a non-empty server summary, and test_prompts_user_content_evidence_validates_server_provenance_and_total covers both mapping and real Pydantic response shapes. Returning HAS_USER_CONTENT here would be a false-positive graduation.

File: tldw_chatbook/Library/library_collections_service.py [hunk 4]
```diff
@@ -199,6 +206,27 @@ def list_collections(
...
+        Returns:
+            Evidence that active local Collections exist or are
+            authoritatively absent.
+        """
+        try:
+            with self.db.connection() as conn:
+                total = conn.execute(
+                    "SELECT COUNT(*) AS count FROM library_collections "
+                    "WHERE deleted_at IS NULL"
+                ).fetchone()["count"]
```
[the remark this answers is not in the document]
Comment (rmusser01) [reply tldw_chatbook/Library/library_collections_service.py:221]: This use of connection() is intentional and follows the narrower LibraryCollectionsDB contract. Its connection() docstring explicitly covers single-statement reads in autocommit mode so they do not pin a WAL snapshot, while transaction() executes BEGIN IMMEDIATE, takes the write lock up front, and explicitly says pure readers must use read_transaction() or connection(). This method performs one COUNT SELECT, so changing it to transaction() would turn a read into a write-locking operation and reduce concurrency. No code change is appropriate here.

**Comment by rmusser01** [comment]
Post-merge regression flagged: **TASK-19602** (filed in PR #1900) — this PR appears to have re-broken `Tests/UI/test_library_prompts_canvas.py`, which TASK-18611 had just fixed (PR #1849). Deterministic local repro on dev@2a15a72bb: 20 failed / 318 passed in the file, including one of the 18611-trio tests. Two new signatures: a `WorkerFailed: 'LibraryHarness' object has no attribute 'app_config'`, and the prompts canvas gating on "workspace registry readiness" that the harness never provides (`#library-prompts-delete-undo` never mounts). Post-merge UI shards were still pending at merge time — worth watching them for confirmation.
